### ISSUE TITLE
Could not obtain lock

### ISSUE THREAD

**Issue by Raphomee** [code4business/xmlimport#4]
Hi,

we're getting the following error when starting the import:
### 

php -f shell/xml_import.php
[2016-04-21 13:04:41] Import started.
[2016-04-21 13:04:41] System process ID: 29940
[2016-04-21 13:04:41] Number of files found in the import directory: 3
[2016-04-21 13:04:46] Could not obtain lock.
[2016-04-21 13:04:46] Importing will not be performed.
### 

Kind regards,
Raphael

**Comment by domeglic** [comment]
The import will create a [database](https://dev.mysql.com/doc/refman/5.5/en/miscellaneous-functions.html#function_get-lock) lock before importing anything to make sure only one is running.

**Comment by Raphomee** [comment]
Hi,

ok, thanks.
Seems like it would not be removed correctly sometimes.
Can we remove it manually ?

Kind regrads.

**Comment by domeglic** [comment]
Even if the php process running the script exists without closing it (for example a fatal error occurs) the lock will be released.
